### ISSUE TITLE
Link to OSRM matching tools is dead

### ISSUE THREAD

**Issue by ustroetz** [mapbox/osrm-matching-inspection#1]
The link Classifying section of the readme to the OSRM matching tools is dead. Where can I find it?

**Comment by TheMarex** [comment]
That link is actually working, but just going to a repository that is currently private. I need to review some files to make sure there is no non-public testing data included or referenced. :-)

**Comment by ustroetz** [comment]
Thanks! Can I find anywhere else documentation on how to use the matching branch?

**Comment by TheMarex** [comment]
Currently the interface is not stable. I will probably change it in the next few days.
However what should work is to run queries on "http://127.0.0.1:5000/match?loc=lon,lat&loc=lon,lat&loc=lon,lat [...]" And it should return a JSON object with the matched coordinates.

**Comment by DennisOSRM** [comment]
It probably makes sense to build the interface out in `node-osrm`.

**Comment by ustroetz** [comment]
Thanks! Looking forward to a stable version. I guess I close this for now.
