### ISSUE TITLE
Missing leaflet-routing-machine.css

### ISSUE THREAD

**Issue by ustroetz** [mapbox/osrm-matching-inspection#5]
[`classify.html`](https://github.com/mapbox/osrm-matching-inspection/blob/master/classify.html#L7) is trying to get `leaflet-routing-machine.css`. Either the file is no longer necessary or it is missing.

**Comment by TheMarex** [comment]
Oh yeah thats not necessary anymore. Thanks! Fixed ce6745c017d3dd4ad7ece9a6417f77f502a49741.
